.TH CONKY-MANAGER2 "1" "Sep 2021" "conky-manager2 2.73" "User Commands"
.SH NAME
Conky-manager2 \- Manage configuration and themes for Conky

.SH SYNOPSIS
.B conky-manager2

.SH DESCRIPTION
.BR Conky-manager2
is a utility to manage themes and configurations for
.BR Conky,
a free, light-weight system monitor for X, that displays
information such as text, icons, progress bars and graph widgets on
your desktop.
.BR Conky-manager2
is a fork of the original Conky Manager
by teejee2008 (Tony George), but provides support for the newer
Lua-based configuration files of
.BR Conky
version 1.10.

.BR Conky-manager2
is written in the Vala programming language.

.SH AUTHOR
Original version by Tony George (teejee2008@gmail.com),
newer fork maintained by 2018 Scott Caudle (zcotcaudle@gmail.com).

.SH "REPORTING BUGS"
When reporting bugs, please raise an issue report at github:
<https://github.com/zcot/conky-manager2/issues>

.SH COPYRIGHT
Copyright \(co 2018 Scott Caudle (zcotcaudle@gmail.com)
.br
Copyright \(co 2013 Tony George (teejee2008@gmail.com)

.SH "SEE ALSO"
The full documentation for
.B conky-manager2
is maintained at github, see <https://github.com/zcot/conky-manager2>
for further information.
.PP
Also see man page for
.BR conky(1).
