rm -f  "/usr/bin/conky-manager"
rm -f  "/usr/share/applications/conky-manager.desktop"
rm -f  "/usr/share/pixmaps/conky-manager.png"
rm -rf "/usr/share/conky-manager"
rm -rf "/usr/share/doc/conky-manager"
rm -f  "/usr/share/locale/*/LC_MESSAGES/conky-manager.mo"
