sudo rm -f  "/usr/bin/conky-manager"
sudo rm -f  "/usr/share/applications/conky-manager.desktop"
sudo rm -f  "/usr/share/pixmaps/conky-manager.png"
sudo rm -rf "/usr/share/conky-manager"
sudo rm -rf "/usr/share/doc/conky-manager"
sudo rm -f  "/usr/share/locale/*/LC_MESSAGES/conky-manager.mo"
